name: Psilva
description: Sobre qualidade de software e a vida!
meta_description: "Testes, Qualidade de Software, Agile"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://pedrro.github.io'
google_analytics: 'UA-70316402-1'
disqus: true
disqus_shortname: 'pedrro'

# Details for the RSS feed generator
url:            'http://pedrro.github.io'
author:         'Pedro Silva'
authorTwitter:  'pedrohns_'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
gems :
  - jekyll-paginate
